### ISSUE TITLE
Platform codes for non research vessels

### ISSUE THREAD

**Issue by CiaranOD** [ices-eg/wg_WGAcousticGov#13]
This issue was originally raised and has now been refreshed again for review. The issue relates to the submission of data collected on non-research vessels including commercial charter fishing vessels that do not have **platform codes**.  It was suggested that IMO codes could be used to fit this purpose. 

Another aspect is for the provision of what could be termed a 'dummy' survey code to allow the upload of survey data related to for example pilot or trial survey programs that are not used into the stock assessment process. 

The ICES DB will investigate the potential of including this going forward @HjalteParner

**Comment by CiaranOD** [comment]
Platform codes using IMO numbers for fishing charter vessels from Steve Mackinson 

###### STARTS ###
Hi Ciaran,

Following the acoustic gov conversation at WGIPS, I think it was a task on me to supply this vessel list for inclusion as acoustic platform in the ICES vocab file.    They all should be associated with the 6aSPAWN survey and also with a ‘dummy survey’ so that there is the possibility to at least upload files and get required stox outputs.

All the best,

Steven Mackinson
Chief Scientific Officer
Scottish Pelagic Fishermen’s Association
Email: steve.mackinson@scottishpelagic.co.uk 
Mobile: +44 (0)7450 683963
 
[Scottish and NI pelagic vessels list.xlsx](https://github.com/ices-eg/wg_WGACOUSTICGOV/files/6030439/Scottish.and.NI.pelagic.vessels.list.xlsx)

###ENDS ###

**Comment by cekv** [comment]
Hi,
I will encourage you to become a registered requester and request platform codes for the vessels on the list
Contact  accessions@ices.dk to create a login to the Code Request Management site https://vocab.ices.dk/Request/ 
The process is quite lengthy, so if the requests are urgent, we need to be informed separately from the above mentioned email

BR,
Cecilia Kvaavik
ICES Data Officer

**Comment by jmjech** [comment]
If you want me to look up the NOAA contacts and see where/who they are, I can do that. I may not be able to do anything about it, but we can see.

**Comment by HjalteParner** [comment]
@jmjech I have forwarded your offer to @Osanna123 who is in the lead of the platform request system at ICES
