### ISSUE TITLE
WGBIFS - HaulCodendMesh

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/wg_WGAcousticGov#14]
Hi Hjalte,

There has raised a question about the mesh size in the codend. There is no further explanations, which of the 3 possible ways it should be given/measured (length of mesh side (bar length)/length of mesh/opening of mesh).
I think that all the descriptions in the ICES vocabularies should be revied. Quite often they are misleading or just not explaining good enough.

Cheers
Olavi

Från: Elor Sepp [mailto:elor.sepp@ut.ee] 
Skickat: den 10 december 2020 12:29
Till: Beata Schmidt <bschmidt@mir.gdynia.pl>; Olavi Kaljuste <olavi.kaljuste@slu.se>
Ämne: Mesh size

Hi Beata, I am forwardint the question to Olavi also.

I actually do not know since it is not explained in the biotic data format also. I have used the mesh size „knot to knot“ (6mm in case of Baltica), but I am not sure any more.
Olavi, you probably know the quick answer to this, I assume that is one more thing we have to check in all uploads (at least tell the uploaders to check).

Elor

Saatja: Beata Schmidt
Saadetud: neljapäev, 10. detsember 2020 12:50
Adressaat: Elor Sepp
Teema: ODP: WGAcousticGov meeting agenda

Hi,
I have another question about biological data file - in section haul there is column "HaulCodendMesh" we should report mesh size i.e. 6 mm or stretched mesh size i.e. 12 mm. I checked in Acoustic data base and Germany report 20 and 12mm (for SD 24 and others respectively) whereas Sweden 6mm. I know it is detail, but I would like to have all according to rules.
Regards
Beata

**Comment by jmjech** [comment]
This is a good question. Hopefully someone in our group is a "net" expert, otherwise it may be useful to loop someone from WGFTFB in on the question. I have a feeling that the measurement should be stretched mesh, as I think that is how the meshes are measured in the net body.

**Comment by elorsepp** [comment]
I think the most important issue here is to have a formal agreement on which measurement is used to avoid having different values for same thing in the database.

**Comment by jmjech** [comment]
If you can enforce which measurement is used, then allowing only one type of measurement is best. If you can not enforce that, then I think you'll need to add an additional field that indicates which measurement it is.

**Comment by CiaranOD** [comment]
I received an answer to this question from a fishing gear expert at the FAO. To me at least, the answer is clear we should be **reporting stretched mesh opening** when reporting mesh size.

###STARTS#####

Hi Ciaran, 
Thanks for the mail.  Right now I’m not working for MFRI in Iceland but for FAO. Still, always with my left eye on the institute inbox ;-) . 

This is a good question and I’m sure there is a lot of confusion ongoing around this.  It is amazing as this have been in discussion for decades.  I sometime feel that many who are registering data for trawl surveys, are like carpenters not knowing the tape measure is in mm or inches! 
However,  this can be confusing for those not working with trawls every day. 
**All databases in scientific work should be given in stretched opening of mesh.  And that is how most of the FTFB community is using it.** 
The bar length or the length of mesh would be used by all employers of net lofts and possible fishers are well as that is telling you how long the whole panel is when building the trawl.   Example  50mm of stretch whole length and 100 meshes long would be 5000 mm or 5 meters or the net. 
But the opening could be 47 or even 45mm for this mesh, depending of twine thickness and knot size.   

From trials we know that only few millimeters in different opening of mesh can have significant different on selectivity of small sizes animals. 

If further questions or more in detail explanations, just send another mail.   

Best regards,
Haraldur 

Haraldur Arnar Einarsson
Fishing Gear Expert
Fishing technology and operations team (NFIFO)
http://www.fao.org/responsible-fishing/
Fisheries Division (NFI)
Food and Agriculture Organization of the United Nations (FAO)
Viale delle Terme di Caracalla Rome 00153, Italy
& Home office, Iceland
Pers-Mob tel: +354 8920503
 
####ENDS#####

**Comment by CiaranOD** [comment]
This will be updated in the documentation for future user reference.

**Comment by HjalteParner** [comment]
@odontaster will you please apply the required elaboration in the biotic documentation?

**Comment by odontaster** [comment]
@HjalteParner will do and close the issue when implemented.

**Comment by odontaster** [comment]
Done now
