### ISSUE TITLE
New spp codes for reporting of Mesopelagic fish

### ISSUE THREAD

**Issue by CiaranOD** [ices-eg/wg_WGAcousticGov#15]
The WGIPS coordinated IBWSS survey will begin the process of reporting on mesopelagic fish (Acoustic & Biotic) to the ICES DB in 2021. This will include species-specific reporting in acoustic  (3 letter ASFIS codes) and biotic (numeric Aphia codes) vocabularies. A list of species will be provided to the DB for inclusion into the species vocabularies.

**Comment by HjalteParner** [comment]
https://github.com/ices-eg/DIG/issues/64
