### ISSUE TITLE
AC_AgeSource

### ISSUE THREAD

**Issue by CiaranOD** [ices-eg/wg_WGAcousticGov#16]
A requirement exists for a new code to be added to the existing (Otolith, Scale, Vertebra) list: ALK (Age Length Key)

As not all species are aged at the time of input into the DB there is a reliance on the use of existing ALK to determine age. For Ireland, this relates specifically to Boarfish but maybe of interest to other nations also.

**Comment by CiaranOD** [comment]
Update as requested. This is a historic (2012) age length key

**Comment by HjalteParner** [comment]
Will take it to the vocab group at https://github.com/ices-eg/DIG/issues

**Comment by SMLusseau** [comment]
I am not sure I agree that it is a good idea to add interpolated data in the data base as an observation on individual fish. Is this not better applied at the analysis stage (for example using the Age Length key with the numbers at length outputs from StoX)?

**Comment by CiaranOD** [comment]
The suggestion is that the application of age is done outside of the database, i.e. within StoX and so keeping the database only for valid aged fish.
