### ISSUE TITLE
Downloads acoustic and biotic data from ICES Data Portal - https://data.ices.dk by area and/or species?

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/wg_WGAcousticGov#21]
Currently acoustic and biotic data in ICES Acoustic Trawl Database can be viewed and downloaded from either ICES Acoustic Trawl Data Portal - https://acoustic.ices.dk as well as from ICES Data Portal - https://data.ices.dk by Cruise followed by a disclaimer including a link to the survey coordinating group as well as the country collecting the data.

There have been a request from the DIG if acoustic and biotic data could be downloaded for a given area and/or species instead of only by cruise? https://github.com/ices-tools-dev/ICES_DataPortal/issues/22#issuecomment-848590155

Would that comprimise how the data from acoustic survey can be used?

**Comment by sindrevatnehol** [comment]
Hjalte. 

I would strongly suggest that only the full cruise data can be downloaded (no subset or filtration!!!). 
These data are related to a survey design and the data has a meaning according to that design. 

We must remember that 0-values has a valuable information the way we are collecting our data. Filtration on species would thus remove an important information. 

At IMR we have the same request for our database. 
Our working solution is to allow for searching for species, but the user will only get the complete dataset. Such solution can also be adopted by ICES. That indicate that if a user search for species ‘X’ the user will get the complete dataset for i.e. HERAS 2020 survey if that species has at least one entry. The user will then get the data that is needed, but in the context the data where collected.

**Comment by HjalteParner** [comment]
Sindre, thanks for your view. FYI this is exactly how it's also done at ICES currently!

**Comment by CiaranOD** [comment]
Hi Hjalte,

I agree fully with Sindre.

Cheers,

Ciaran
