### ISSUE TITLE
Call to Survey planning groups (WGIPS/WGBIFS/WGACEGG) on biological sampling

### ISSUE THREAD

**Issue by CiaranOD** [ices-eg/wg_WGAcousticGov#23]
Linked to ...
#7 
#12 
#20

**Comment by CiaranOD** [comment]
The collection of biological at sea and how these data are handled nationally and for upload to the ICES portal requires description. Getting a handle on how data are collected, structured and manipulated prior to upload at a national level will require input from the Survey planning Groups.  To that end, a recommendation from this group to WGWIPS, WGBIFS and WGACEGG requesting this information will be circulated. Your input is required in this process ! This fits with the recent request from DATRAS.

Main points:
3 main questions to be address to institutes:

1 - What is the biological sampling process? Especially, is length sampling correlated to further biological sampling (age, weight, maturity)

2 - Is LF and biological sampling stored separately in a local database

3 - Is there currently a need to manipulate data to fit the ICES db and if so how?

Please add you thought here......

**Comment by CiaranOD** [comment]
[Recommendation to survey planning groups_BIO sampling methods.docx](https://github.com/ices-eg/wg_WGACOUSTICGOV/files/7395611/Recommendation.to.survey.planning.groups_BIO.sampling.methods.docx)

Recommendation as sent to the chairs of WGIPS, WGACEGG and WGBIFS 22.10.21

**Comment by CiaranOD** [comment]
I attended WGACEGG (online meeting in Nov) and got feedback on sampling strategies in place on each of the surveys coordinated by the group. Currently, only IRL and UK from this group are regular contributors to the ICES DB so it was somewhat limited, given we are aware of the background issues.  

I'll upload this file to the Sharepoint shortly (see 2021-Data) and this can be used as a template for contributions from the other groups.
If this information were available ahead of the 2022 meeting dates this might speed up the process somewhat.
           January 2022: WGIPS
           March 2022:   WGBIFS

I will circulate reminders to WGIPS and WGBIFS group chairs and include the template for input closer to the meeting dates.

**Comment by HjalteParner** [comment]
Will be continued in #40
