### ISSUE TITLE
Standardisation of survey outputs

### ISSUE THREAD

**Issue by CiaranOD** [ices-eg/wg_WGAcousticGov#24]

**Comment by CiaranOD** [comment]
Email circulated by the Chairs of WGIPS on 1st Sept to WG members requesting input on the standardisation of survey outputs:

Dear WGIPS members,

Ciaran as chair of AcousticGov in consultation with Espen have been discussing within their group how we can standardise reporting of survey results from StoX in a structured format across our surveys. Given StoX has now moved to R, this is timely and something Espen and the StoX developers are keen on supporting. Not only would suitably developed scripts standardise how we report but it would also feed into TAF.  This could reduce the time spent at our already busy post-cruise meetings making maps and figures, and leave more time for discussion on the surveys. 

As WGIPS are the core StoX user group we think this is the best starting point. Rather than bring this up for discussion cold at the next WGIPS meeting we thought we’d try and get a bit ahead by looking to the survey coordinators for contributions and feedback, the aim being that we would have something to present at our next meeting rather than just talking about it.  It would also be good to schedule some time at the meeting in January to discuss this with the wider group if possible. 

We have support for this within the ICES datacentre to get things moving on the scripting front. So to move this forward, we’re requesting input from the survey coordinators. At this point we are looking for the standard tables and figures that people would like to see scripted. We know for some of the coordinated groups scripts likely already exist and they can feed into this process.

Within WGIPS we have a GitHub site ready to go (https://github.com/ices-eg/wg_WGIPS/tree/8a4419c2aed75d5fb2101ba45224d671c548dfba/R) and we can set up a folder on the Sharepoint also where examples can be uploaded and we can follow up at our next meeting. 

If we could ask for feedback particularly from the survey coordinators, but anyone interested in contributing by Friday 17th September, that should allow time for people to consider what they would like from this product in the future. 

Regards,

Mike and Bram

**Comment by CiaranOD** [comment]
Follow-up email sent on the 10th Sept to WGIPS Survey Coordinators (IBWSS, IESNS, IESSNS & HERAS) 

Dear All,

Following on from previous Mike’s email, I’m writing to you as survey coordinators to encourage you and your members to participate in the exercise to develop a standard reporting format for key survey outputs. 

Details are in the email below and we have asked for responses by next Friday (17th Sept). This will get the process started and we hope to further it between now and the next WGIPS in January.

All the best,

Ciaran

**Comment by CiaranOD** [comment]
A response was received from HERAS Survey Coordinator (Germany) on 14 September.

**Comment by CiaranOD** [comment]
Code is being developed within current survey user groups to reach the same outcome (reporting of common maps, tables & Figs). For those willing to share code, it would be useful to upload to the Gov (or other) GitHub site so that they can be shared and developed. Ciaran O'D will raise at the WGIPS meeting in Jan 2023.

**Comment by HjalteParner** [comment]
Not enough responses to make sufficient progress. The issue / task will be handled in another way. Possible from survey groups into survey coordination groups and further into the governance group as seen fit.

An estimate is that at least 75 % of the plots in postgroup reports could be shared! So defenitly seems worth to make a common library / package to be share - especially when abundance estimate start using TAF @colinpmillar @cekv
