### ISSUE TITLE
Gridfile data

### ISSUE THREAD

**Issue by CiaranOD** [ices-eg/wg_WGAcousticGov#26]
Grid file data (acoustic effort and acoustic density) are used within WGACEGG during the annual reporting cycle and form an important and valuable component of the groups work. These time-series data highlight species distribution of SPF and changes in distribution over time. These data are currently hosted by IFREMER (by nation, by survey, by year) and a request has been submitted to explore how these data could be are hosted by ICES in the future.

**Comment by HjalteParner** [comment]
How are these grid file data created? Are they created based on survey data? Something else? I'm wondering if these data / figures isn't a perfect match for being created in TAF in an annual repository? I guess they might even already be created by an R script?

**Comment by CiaranOD** [comment]
Hosting historic time series data;
Best starting point is to generate a recommendation within the group for the attention of the ICES data centre

**Comment by CiaranOD** [comment]
To be raised at WGACEGG Nov 2022 by Ciaran O'D
