### ISSUE TITLE
Exclude parts of data from analysis in StoX/separate csv-xml converter

### ISSUE THREAD

**Issue by elorsepp** [ices-eg/wg_WGAcousticGov#36]
I would like to conduct some experiments based on our survey data in StoX. I would like to exclude some hauls/ESDU-s and see the effect on results. It seems difficult since, in my understanding, StoX uses all the data that the file contains. 

Is there a way to choose which data points to exclude from the analysis in StoX?

Or could we have a separate csv - ICES xml converter to make a new raw data file with excluded data? I would not like to export unnecessary experiments to the database.

**Comment by CiaranOD** [comment]
Elor will send a direct request to the StoX team for assistance.  StoX GitHub site will be developed with R StoX Utilities for simulation study packages to assist with survey sensitivity testing and sampling variance.

**Comment by HjalteParner** [comment]
Done by csv conversion without upload
