### ISSUE TITLE
Draft the framework

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/wg_WGAcousticGov#4]
agree on section headings, and assign authors to each section to work on inter-sessionally

**Comment by neil-ices-dk** [comment]
examples:
TAF governance working [example of framework](https://docs.google.com/document/d/1Bip1rRMmRWeSIX1BphD4h24d0v0tzRsqvB6fah4RZcs/edit#heading=h.an1ipzjm369j)

WGSFD (Spatial Fisheries) [example here](https://docs.google.com/document/d/1gjZrM27fHSE67ocMYQwMQT0_3VRe2ySjHV87vv1OtiM/edit#heading=h.33s429uhzk5d)

**Comment by neil-ices-dk** [comment]
The draft working document for the framework is availble in [Google Docs](https://docs.google.com/document/d/1y_ZizY-EkDynsZJYW6AK4PXqCTvJqMIPOHAdzvh_gD4/edit?usp=sharing)

based on

> WGSFD (Spatial Fisheries) example here

**Comment by neil-ices-dk** [comment]
@CiaranOD to assign names to the headings for drafting text 👍

**Comment by CiaranOD** [comment]
I consider this as a closed item now given the review period and feedback opportunity, I will present this document during @meeting 2 

[WGACOUSTIGOV Framework_FINAL.pdf](https://github.com/ices-eg/wg_WGACOUSTICGOV/files/5672135/WGACOUSTIGOV.Framework_FINAL.pdf)
