### ISSUE TITLE
Biotic submission, missing WORMS species in ICES database

### ISSUE THREAD

**Issue by JanArge** [ices-eg/wg_WGAcousticGov#41]
When submitting Biotic to ICES very often species (legal WORMS species) are missing in the ICES database. This creates unnecessary delay in submission to the database, as the species has to be "created" in the ICES database by ICES before it is possible to submit the Biotic file. As an example for the blue whiting survey, the Biotic file has to be available a week after the survey finishes in order to be ready for the postcruise meeting, so any unnecessary delay should be avoided.

All (aquatic) WORMS species should be loaded into the ICES database to avoid this situation.

**Comment by HjalteParner** [comment]
I agree Jan Arge and I think a solution like this is on the way.

@mehdiabbasi can you give a status on this?

**Comment by mehdiabbasi** [comment]
Soon will be implemented, just waiting @odontaster to confirm by the RDBES team also

**Comment by odontaster** [comment]
Hi @mehdiabbasi, I presented the suggestion to RDBES team but I believe that their submission system does not make it easy to retrieve the missing aphiaIDs on the fly. I do not believe they will try to implement this any time soon. I hope this can move forward for the Acoustic database if their system allows it.

**Comment by HjalteParner** [comment]
In the pipeline

**Comment by JanArge** [comment]
-how long is the pipe ;-)

**Comment by HjalteParner** [comment]
Done
