### ISSUE TITLE
Population code

### ISSUE THREAD

**Issue by florianberg** [ices-eg/wg_WGAcousticGov#48]
At WKSIDAC2 we have identified several herring genetic units that we would like to upload to the database. The problem with these genetic units is that they do NOT match the current "stock code". Therefore, we wish to have a new optional field to add information about the genetic unit. This population code will be some sort of vocabulary which however will be dynamic and might be adjusted over time. Such a population code will also be valid for other species. Also this code might be added in the acoustic, datras or egg/larvae database.

**Comment by HjalteParner** [comment]
On top of my head, I think making an optional field for a population vocabulary code makes sense.

Let's discuss at next governance meeting in september.

@florianberg could you in the meantime give us some more details on the (if I understands correctly) 26 or so initial identified herring population which possible would enable us to come up with a sugested coding system like the one currently used for the ICES stock codes?

@annecooper and I quckly talked about the ices stock code naming convention and I think she will be a good help creating a simelar naming convention for the population codes.

@odontaster is part of the vocabulary manegement code and they will discuss this in one there upcoming meetings.

**Comment by HjalteParner** [comment]
https://github.com/ices-eg/DIG/issues/478

**Comment by florianberg** [comment]
Yes, we have currently 26 herring populations that would need a  code. Most of them will not change over time, but a few of them might be updated/replaced. We had a short chat with @annacopper today at the meeting about these codes. I have attached an Excel file with information about the different populations and a suggested "ICES.population.code" for some of them. The first part is identifying that these are herring groups, the last part is identifying the spawning time (spring, summer, autumn, winter), and the middle part is currently reflecting the area of spawning (Lat/Lon for known spawning ground are provided in the Excel file). These are suggestions brought forward by the WKSIDAC group. When we tried any naming convention we got some issues when different populations would end up with the identical code. We are open to any input. 
[Herring baseline samples.xlsx](https://github.com/ices-eg/wg_WGACOUSTICGOV/files/11849662/Herring.baseline.samples.xlsx)

**Comment by odontaster** [comment]
https://github.com/ices-eg/DIG/issues/478

**Comment by odontaster** [comment]
This is almost implemented. Waiting for feedback from RDBESgov, as they need it as well.

**Comment by HjalteParner** [comment]
Have been implemented
