### ISSUE TITLE
WGBIFS request for format change - Add BiologyIndividualWeightHow

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/wg_WGAcousticGov#7]
WGBIFS recommends to ICES Data Centre to add a new field into the biotic data format of ICES data base for acoustic survey data. This new field would specify whether the values given in the “BiologyIndividualWeight” field are measured as individual weights or as mean weights of current length-class. This would allow countries, which perform biological sampling during the surveys and are unable to measure fish individual weights with sufficient accuracy, to upload measured mean weight at length information into the data base.

**Comment by CiaranOD** [comment]
We had to park this issue until our Feb meeting as no one was present from WGBIFS to discuss

**Comment by CiaranOD** [comment]
Parked for review at next meeting as requires some thought on how to progress.

**Comment by CiaranOD** [comment]
So issue will be considered alongside comments from DATRAS

**Comment by CiaranOD** [comment]
This issue would come under the umbrella of the wider issue of 'Biological sampling at sea' and how we sample on survey.

**Comment by odontaster** [comment]
@CiaranOD and @HjalteParner I might show some examples of reporting instances in case we already have a viable solution in the format as is.

[Biotic_FormatandExamples.xlsx](https://github.com/ices-eg/wg_WGACOUSTICGOV/files/7675131/Biotic_FormatandExamples.xlsx)

**Comment by odontaster** [comment]
https://github.com/ices-eg/wg_WGACOUSTICGOV/issues/40
