### ISSUE TITLE
WGIPS HERAS request / comments catch up

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/wg_WGAcousticGov#8]
[Meeting with Hjalte about HERAS in ICES database.docx](https://github.com/ices-eg/wg_WGACOUSTICGOV/files/5642551/Meeting.with.Hjalte.about.HERAS.in.ICES.database.docx)

**Comment by CiaranOD** [comment]
This document was reviewed during WGIPS and action points have been already covered within the current PBI list.
